# Generated by Django 4.2.5 on 2023-11-12 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=20)),
                ("head_count", models.IntegerField()),
                ("live_start", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
