# Generated by Django 4.2.5 on 2023-11-13 10:18

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_register_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="user_img",
            field=models.FileField(upload_to=user.models.user_directory_path),
        ),
    ]
