# Generated by Django 4.2.5 on 2023-11-13 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_register_user_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="parent",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_register",
            name="user_id",
            field=models.CharField(max_length=20),
        ),
    ]
