# Generated by Django 4.2.5 on 2023-11-13 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_user_register_parent_alter_user_register_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20)),
                (
                    "user_model",
                    models.FileField(upload_to=user.models.user_directory_path),
                ),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
    ]
