# Generated by Django 4.2.5 on 2023-11-13 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_user_model_user_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_model",
            name="model_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
